// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewsxturdyvonoaehedft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3c3h0dXJkeXZvbm9hZWhlZGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTUxOTUsImV4cCI6MjA2NzQzMTE5NX0.1yYEKtraJ48Dqcx2VSSskaKRm4zVPOZ4Wo8c85lz7dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});